//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManagerCompanyDBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartman()
        {
            this.Islers = new HashSet<Isler>();
        }
    
        public int AptNo { get; set; }
        public string AptAd { get; set; }
        public Nullable<int> daireS { get; set; }
        public Nullable<int> katS { get; set; }
        public string adres { get; set; }
        public Nullable<bool> asansor { get; set; }
        public Nullable<bool> havuz { get; set; }
        public Nullable<bool> sporS { get; set; }
    
        public virtual AptYoneticiler AptYoneticiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Isler> Islers { get; set; }
    }
}
