//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManagerCompanyDBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AptYoneticiler
    {
        public int aptNo { get; set; }
        public string yoneticiAd { get; set; }
        public string telefon { get; set; }
        public Nullable<int> daireNo { get; set; }
    
        public virtual Apartman Apartman { get; set; }
    }
}
