//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManagerCompanyDBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hizmetler()
        {
            this.Islers = new HashSet<Isler>();
        }
    
        public int hizmetNo { get; set; }
        public string hizmetAdi { get; set; }
        public Nullable<decimal> hizmetUcret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Isler> Islers { get; set; }
    }
}
