//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManagerCompanyDBfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isler
    {
        public int isNo { get; set; }
        public Nullable<int> aptNo { get; set; }
        public Nullable<int> calisanNo { get; set; }
        public Nullable<int> hizmetNo { get; set; }
        public Nullable<int> isGün { get; set; }
        public Nullable<System.DateTime> baslangicT { get; set; }
        public Nullable<System.DateTime> bitisT { get; set; }
    
        public virtual Apartman Apartman { get; set; }
        public virtual Calisanlar Calisanlar { get; set; }
        public virtual Hizmetler Hizmetler { get; set; }
    }
}
