//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManagerCompanyDBfirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptManagerCompanyEntities : DbContext
    {
        public AptManagerCompanyEntities()
            : base("name=AptManagerCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartman> Apartmen { get; set; }
        public virtual DbSet<AptYoneticiler> AptYoneticilers { get; set; }
        public virtual DbSet<Calisanlar> Calisanlars { get; set; }
        public virtual DbSet<Hizmetler> Hizmetlers { get; set; }
        public virtual DbSet<Isler> Islers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
    }
}
